### ISSUE TITLE
Image Uploader enhancements

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#113]
I have a few ideas that will allow us to bring back PNG uploading. Before, the big issue was that the image cropper would _always_ process the image, even if it the user chose not to crop it. This would usually result in larger images than the original filesize. So, with that in mind, some ideas:

1) If the cropper is set to the image's original dimensions, don't use the cropper's interpretation of it. Just base-64ify the image ourselves, and use that instead.
2) In addition, add a "current filesize" display that updates every time the user changes the cropper's dimensions. This will give users more immediate feedback. This will need to switch between the cropper's processed image, or the originally-selected image, based on whether or not the image has been cropped or not.

If we do this, I think we can restore the code that lets the cropper pass the image through with changing its file format.

**Comment by Figments** [comment]
wanted to add that some people still can't upload avatars

**Comment by Figments** [comment]
this requires re-evaluation. as it stands, the image uploader appears to be working as intended.
