### ISSUE TITLE
Revisit author's note character limits

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#125]
We've already had one author bumping up against the character limit, so we may want to raise/remove it.

Additionally, we need to teach our logic to either a) count words and communicate limits in terms of that, or b) count characters that _don't_ include all the Quill nonsense (which is probably a utility function that belongs in our Rust word_counter).

**Comment by Figments** [comment]
yup! sounds like a good idea, we can use voca_rs in the word counter module to count string characters after parsing through the delta.

**Comment by SigmasonicX** [comment]
With limits removed, there's no need to count characters.
