### ISSUE TITLE
Make section publish/edit errors not trap users in infinte loads

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#126]
For example, right now, a too-many-characters error when publishing a section breaks the page to the point that a refresh is necessary.

**Comment by Figments** [comment]
Closed as of the release of 0.2.1

**Comment by pingzing** [comment]
This still happens on edit errors. To repro:

- Go to edit a section.
- Erase the title.
- Attempt to publish.
- Spin! Forever!
