### ISSUE TITLE
Adjust azure pipelines to fit the new build environment

### ISSUE THREAD

**Issue by Figments** [OffprintStudios/dragonfish#127]
PINGZING EDIT:
Partly addressed by #136.
A to-do list for what remains:

- [x] Reconfigure the server to serve up static content from somewhere (a static subfolder?) where the frontend will be served from
- [x] Reconfigure local dev builds of the client to output themselves to this static subfolder for easier dev purposes
- [x] Reconfigure the Azure DevOps Releases to deal with the new folder structure from the adoption of nx

**Comment by pingzing** [comment]
Partly addressed by #136.

**Comment by pingzing** [comment]
A to-do list for what remains:

- [ ] Reconfigure the server to serve up static content from somewhere (a `static` subfolder?) where the frontend will be served from
- [ ] Reconfigure local dev builds of the client to output themselves to this `static` subfolder for easier dev purposes
- [ ] Reconfigure the Azure DevOps Releases to deal with the new folder structure from the adoption of `nx`

**Comment by Figments** [comment]
Closed with the move to Render
