### ISSUE TITLE
Extra newlines with the new text blot for Quill

### ISSUE THREAD

**Issue by Figments** [OffprintStudios/dragonfish#128]
1) Sometimes block quotes generate an extra newline even though in the editor there aren't any extras:

<img width="612" alt="Screen Shot 2020-08-23 at 8 06 33 PM" src="https://user-images.githubusercontent.com/2677783/90999766-57cd5000-e57c-11ea-9418-a5cdae2a9c61.png">
<img width="612" alt="Screen Shot 2020-08-23 at 8 06 43 PM" src="https://user-images.githubusercontent.com/2677783/90999768-5a2faa00-e57c-11ea-8a6b-3b9c43694988.png">

2) when opening a new quill editor instance, sometimes a newline is placed for no reason:

![Screen-Recording-2020-08-23-at-8](https://user-images.githubusercontent.com/2677783/90999893-b4c90600-e57c-11ea-8f3b-8fed42261f5b.gif)

**Comment by Figments** [comment]
@pingzing You might want to take a look at this

**Comment by pingzing** [comment]
Also seen:
- Authors notes always starting with an empty newline
- HTML paste from other sources beginning with a stray newline
