### ISSUE TITLE
Pasting text from AO3 triggers strange formatting issues

### ISSUE THREAD

**Issue by Figments** [OffprintStudios/dragonfish#131]
<img width="1040" alt="Screen Shot 2020-08-26 at 6 32 20 PM" src="https://user-images.githubusercontent.com/2677783/91373211-a4a66600-e7ca-11ea-8f2c-a814ded99480.png">

**Comment by pingzing** [comment]
A note from my own observations:

If an italicized word is the final word in a paragraph, it will make everything after it italicized too. There's probably a lead we can chase down there.
