### ISSUE TITLE
Users cannot embed images under certain scenarios

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#137]
Per SigmasonicX
> I copied text from FimFiction's editor, then tried to embed an image among that text (creating a newline between paragraphs and putting the image there) and it didn't work.
OK, so after creating a double-newline, I was specifically able to put the image there
I can't put an image on a single-newline
This applies to single-newlines created with Shift+Enter too

Might have something to do not being able to embed an image at the end of a block, perhaps?

**Comment by Figments** [comment]
Closed with the migration to CKEditor 5
