### ISSUE TITLE
Security: Add salt to user hash

### ISSUE THREAD

**Issue by nisamson** [OffprintStudios/dragonfish#17]
Currently, we're not salting the password hashes; we'll almost certainly want that to harden the auth database.

**Comment by Figments** [comment]
Passwords are salted via the `argon2` library, which includes the salt alongside the password when it returns the hash. You can check the DB to verify this when you create a new user.

Please confirm you're seeing this, so I can close this issue out if so.

**Comment by nisamson** [comment]
Ah, I see; I misunderstood how the `argon2` hash function works. Confirmed that it's using a salt.
