### ISSUE TITLE
Update icons that use "title" for tooltips to use "matTooltip"

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#172]
There is a mix of icons that use "matTooltip" for tooltips and icons that use "title". We would like to use "matTooltip" consistently. It's still unclear if we want to remove the uses of "title". Having both will result in duplicate tooltips.

**Comment by Figments** [comment]
We're using matTooltip wherever necessary, and adding it in places as we create new parts of the site.
