### ISSUE TITLE
Write "What is Offprint?" page

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#194]
New users have mentioned trying to find out what Offprint's deal is, only to be stymied by the "What is Offprint?" page being empty. There should be a description of the site's goals.

The target audience of this description should primarily be users coming from AO3, as FimFiction users generally see "FimFiction but generalized" as worthwhile on its face.

**Comment by SigmasonicX** [comment]
https://docs.google.com/document/d/1zDOBLi7q0prF9I-Vdal5PSfSLDG2nExvSqzmT-B9oQU/edit?usp=sharing

**Comment by Figments** [comment]
looks good enough to me. adding it in
