### ISSUE TITLE
"Insert media" doesn't work

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#214]
Reported by Krickis:
When using "insert media" to insert a YouTube video into content, this video shows up in the preview, but this disappears when it's actually published.

**Comment by pingzing** [comment]
Solving this one is actually a bit tricky--the embedded media lives inside of an `<iframe>` which contains, well, arbitrary HTML. Genuinely not sure how we can safely accept this without doing some manual whitelisting, beyond what Ammonia (seems?) to allow. Check out the HTML tree below that a YouTube embed generates:

![image](https://user-images.githubusercontent.com/5133649/105505396-93a64600-5cd1-11eb-8d79-ae92e90f6138.png)

A bad actor could pretty trivially send up some dangerous HTML if we just blindly allow iframes.

**Comment by Figments** [comment]
partially fixed with 0.7, we just need to re-enable the media embed button

**Comment by Figments** [comment]
tracking in #435
