### ISSUE TITLE
Text copied from single FimFiction paragraph has background color that can't easily be removed

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#215]
Reported by Krickis:
So when copying stuff over from certain websites it gives this funky highlight, which can not be removed. This is what it looks like when it uses the remove font color and remove highlight options on it. This was copied from Fimfiction (it only does this if copying a single paragraph; if copying two or more paragraphs it copies without issue)
https://cdn.discordapp.com/attachments/690694506231627787/769041616240377866/Screenshot_176.png

I know how to fix it (paste as plain text, manually add the link back in) but it was previously mentioned that the remove highlight option would work on this and it does not

Issue can be seen in the author's note of [this chapter](https://offprint.net/work/cKtqW-LpF/acts-of-love/1/prologue)

---

I suspect this is due to how FimFiction will highlight a paragraph when you click it and give you an option to quote it for a comment.

**Comment by Figments** [comment]
Gonna merge this with #267 since the issues stem from the same necessity of stripping colors from rich text paste.
