### ISSUE TITLE
Dropdown menu text is black after it's selected, so it's hard to see on dark backgrounds

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#244]
![image](https://user-images.githubusercontent.com/71996084/103165679-abbc9f80-47cf-11eb-86ed-0ee576573ec3.png)

After selecting an option from the New Prose dropdown menu, it turns black, and thus can't be seen easily on a black background.

**Comment by TheMajorTechie** [comment]
Fixed in PR #277 .

**Comment by TheMajorTechie** [comment]
New CSS is not being applied to the dripdown menus, but menu items are being properly styled.
