### ISSUE TITLE
In My Stuff, if there are a lot of sections in a work, then it breaks the formatting

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#255]
In My Stuff, if there are a lot of sections in a work, then it breaks the formatting
![image](https://user-images.githubusercontent.com/71996084/103200422-2950e000-48a2-11eb-9db3-d96389b6369e.png)

**Comment by TheMajorTechie** [comment]
I added a scrollbar to fix this issue.
![image](https://user-images.githubusercontent.com/29270676/103318613-38dc4000-49ec-11eb-94b3-f1dfe99bbbae.png)
