### ISSUE TITLE
Work, that was converted to new editor, is messed up after v0.5.1 migration

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#258]
![image](https://user-images.githubusercontent.com/71996084/103245230-550cae00-4914-11eb-9574-b8cee185d9f2.png)

Jetstream is sure that he edited and saved this work to convert to the new editor. Regardless, after migration, the work looks the same as a work that wasn't converted to the new editor.

**Comment by Figments** [comment]
as of #263 , users can now migrate sections using the old editor to the new one. let's leave this here as incentive to migrate.
