### ISSUE TITLE
Works and sections don't display the title in the browser title bar

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#259]
Works and sections don't display the title in the browser title bar

I have found a solution for displaying the work title on the main page, and displaying the section title in the section page, but I have had trouble displaying both the work and section title in the section page. If we don't figure out how to do so, then it is possible to display the work title by not having the section page code set a title; I think it's preferable to display the work name rather than the section name.

**Comment by Figments** [comment]
partially fixed in #263
