### ISSUE TITLE
My Stuff formatting is somewhat broken in Firefox on works with longer descriptions.

### ISSUE THREAD

**Issue by TheMajorTechie** [OffprintStudios/dragonfish#265]
Title says it all. I noticed while going through my "My Stuff" page that works with longer descriptions clash with the stats at the bottom of each card. On Chrome, this is handled by a bit of blurring that hides overflowing text, but this doesn't appear to work properly in Firefox.
![image](https://user-images.githubusercontent.com/29270676/103334896-5fbc6580-4a30-11eb-828d-c39ad630be4e.png)

**Comment by Figments** [comment]
yeah, looks like the blur effect isn't working
