### ISSUE TITLE
Sections lists on a work's landing page display unecessary scrollbars

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#284]
This happens even when there's plenty of vertical space--the sections list has a `max-height` of 500px. See image:
![image](https://user-images.githubusercontent.com/5133649/103468574-17b87e00-4d63-11eb-84cc-8ec1a2cf7164.png)

Two issues: First, the sections list container should have `overflow-y` set to `auto` rather than `scroll`.

Second, there _is_ actually overflow. The culprit here is, oddly, the the chevron icon. Part of the problem is that the icon is not just an icon--it's also a `<button>`. In addition, its styling is incredibly complicated, making it very hard to make it fit in the `<li>` it's parented to, which _seems_ to be resulting in the overflow.

The fix is probably to make the chevron icon just be an icon, and not a `<button>`, and then simplify its styling so that it plays nicely with its parent container.

**Comment by SigmasonicX** [comment]
No longer extant in dragonfish-next

**Comment by Figments** [comment]
resolved in dragonfish-next
