### ISSUE TITLE
Support "Article/Reader" reading views for prose pages

### ISSUE THREAD

**Issue by f-loki** [OffprintStudios/dragonfish#288]
One of the features I use when reading fiction online that enables a consistent reading experience is the "Reader View" in Firefox. 

Currently the website doesn't support this view mode, which for me means I have to engage with the page being very wide on desktop and using a font that I find hard to focus on.

An article on the heuristics used to see if a page can be rendered in reader view can be found here: https://videoinu.com/blog/firefox-reader-view-heuristics/

**Comment by Figments** [comment]
thanks for the tip!

We'll look into it as soon as we can.

**Comment by Figments** [comment]
article mode should now work for all content in all major browsers
