### ISSUE TITLE
Handle Shutdown Gracefully

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#324]
As described in detail here: https://hackernoon.com/graceful-shutdown-in-nodejs-2f8f59d1c357 we need to handle shutdown gracefully now that we have long-running tasks--we need to signal them to stop and finish what they're doing. 

Currently, there is a risk that if we shutdown in the middle of handling a batch of notifications, they'll get marked a `published`, but then the server shuts down before they get copied over to the `notifications` collection, and get lost forever. The Notifications service is already set up to handle this--we just need to be able to tell it "the server is shutting down, pack it up".

We should probably handle `SIGINT`, `SIGTERM` and `SIGHUP`, and make them all do the same thing.

**Comment by Figments** [comment]
graceful shutdowns are now handled by the hosting platform. if a job is still processing, the renewed instance of BullJS will restart the job without fail
