### ISSUE TITLE
Some works with empty author's notes still exist

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#335]
https://offprint.net/prose/UZk_ebnth/old-friends/1/old-friends

This work has an empty author's note. This should result in no author's note present. It's possible there is some invisible character that was included in the author's note.

**Comment by SigmasonicX** [comment]
Unable to recreate, will have to check on the live site

**Comment by Figments** [comment]
haven't been able to see it at all on the live site either, we'll reopen this if someone mentions it again
