### ISSUE TITLE
Long usernames are cut off/push the box to the right for comments.

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#342]
![image](https://user-images.githubusercontent.com/71996084/105625116-c63c6580-5ddb-11eb-8557-4ad5ddd72a24.png)

Following up on https://github.com/OffprintStudios/pulp-fiction/issues/318 , this issue is still present only for unusual aspect ratios. The one in the screenshot is 3:2.

**Comment by pingzing** [comment]
Partially addressed by #514, but can still happen in some sillier cases:

![image](https://user-images.githubusercontent.com/5133649/117536815-f49a2580-b005-11eb-8607-a2a5754ade02.png)
![image](https://user-images.githubusercontent.com/5133649/117536822-fc59ca00-b005-11eb-99a6-c6c2df7df206.png)

The first one is worse, IMO--you lose important information, and it makes the page harder to use.
The second one is... fine? There may be a more elegant solution there, but  it works.

**Comment by Figments** [comment]
honestly i think we should just lower the upper limit for usernames; we might have set that a bit too high.

**Comment by Figments** [comment]
this is no longer possible
