### ISSUE TITLE
Add validation for email field in sign in

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#348]
Almost every user has gotten tripped up when trying to sign in, using their username instead of their email, and being unable to figure out why.

Add a check for an @ and display an error message saying to use a valid email address to sign in if one isn't detected.

**Comment by SigmasonicX** [comment]
In dragonfish-next, the default text being an email address should help address this, but this doesn't account for password managers automatically populating the field with a username. The error message is still generic and doesn't check for @ sign.

**Comment by Figments** [comment]
fixed in dragonfish-next
