### ISSUE TITLE
Investigate reworking the changeNameAndEmail function

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#36]
Per discussion in https://github.com/OffprintStudios/pulp-fiction/pull/33#discussion_r462598288, adding it here so it gets remembered for some time after launch

Would it make more sense to just split this out into two separate functionalities? a `changeEmail` and `changeUsername`, for example?

**Comment by Figments** [comment]
Mm, that might work, though without consolidating the results into a single function we'd have to make separate "Change Username" and "Change Email" forms in a user's settings, and that might just introduce unnecessary clutter

**Comment by pingzing** [comment]
I can think of some ways the that UI could work without being horrible, but I'd have to play with it a bit--not super familiar with what Angular makes easy.

**Comment by Figments** [comment]
Sounds good! Throw up some mockups so I can see what you're thinking.

**Comment by pingzing** [comment]
![emailstuff](https://user-images.githubusercontent.com/5133649/89113212-d13eba80-d476-11ea-9ef3-76cc451be56d.gif)

(oh my god I should not be allowed to touch front-end code this is a monstrosity)

But yeah. Basic idea is that email and username are each their own little self-contained entry. They can be in one of three states:
1) Default. Input area cannot be edited, display whatever's saved, display an edit icon to the right.
2) Editing. Input area can be edited, display both an "accept" and "cancel" icon on the right. Accepting sends you to state 3), cancelling restores the original input and sends you back to state 1).
3) Uploading. Input area cannot be edited, a loading spinner is displayed to the right. If upload succeeds, we update the user object and go back to 1). If upload fails, we go back to 2).

Additional thoughts:

- While in edit mode, the "current password" entry box appears below the box being edited, possibly with some animation or different visual to distinguish it, or draw attention to its appearance? Otherwise, it stays hidden.
- The "save changes" button goes away.

**Comment by pingzing** [comment]
Alternately, the _much_ simpler solution is just to check to see which of the fields have changed, and fire either 1 or 2 separate requests, and just wait for both of them to return.

**Comment by Figments** [comment]
That's honestly not a bad idea, to be honest. Let's definitely add this to the list of things to do post-launch.
