### ISSUE TITLE
Side menu button is confusing when signed out

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#369]
![image](https://user-images.githubusercontent.com/71996084/107162572-1d544580-6959-11eb-99ad-86112d8cfc7b.png)

When the user is signed out, when in a small window or when on mobile, the side menu button resembles a log out button. This is confusing for users.

One solution is to make it a log out button when logged out, even on smaller screens.

**Comment by Figments** [comment]
Resolved with the user in question
