### ISSUE TITLE
Add types to Request

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#37]
This is more of a nice-to-have than anything else, brought about by my confusion about what I can do with request objects in NestJS.

Requests are all of type `Request` from the Express library.

Except for anything protected by `AuthGuard`, `OptionalAuthGuard` or `RefreshGuard`--they (can) rewrite the request object to have an extra `user` object on it, which is of type `JwtPayload`.

All this needs is for someone to go an make an `AuthorizedRequest` interface that inherits from Express's `Request`, and adds an optional `user` object of type `JwtPayload`. Then we can just annotate all our requests with either `Request` or `AuthorizedRequest` and fun times ensue.

(Note: We can use the `@Req()` decorator for NestJS instead of `@Request()` to avoid naming conflicts with the `Request` type. Both `@Req()` and `@Request()` do the same thing anyway.)

**Comment by Figments** [comment]
Might be something to investigate post-launch, sure! Anything to make working with what we got easier.
