### ISSUE TITLE
Franchise tag case studies

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#371]
Case studies for franchises that we should be able to handle with our franchise tag implementation. This isn't to say all of these deserve separate tags, just that we should think about them. How should they be nested? What should be combined?

- My Little Pony: Friendship is Magic, Equestria Girls, My Little Pony: the Movie (2017), My Little Pony: Friendship is Magic (IDW comics)
- She-Ra: Princess of Power (80s), She-Ra and the Princesses of Power (10s)
- Steven Universe, Steven Universe Future
- Jojo's Bizarre Adventure: Phantom Blood, Jojo's Bizarre Adventure: Steel Ball Run, original JJBA story that has stands but no existing characters
- Cheers, Frasier
- Batman: the Animated Series, nonspecific Batman story, Batman v Superman: Dawn of Justice, Justice League (comics), Justice League (animated series), Justice League (2017), Zack Snyder's Justice League (2021)
- Crossover between 6+ franchises
- Crossover between a franchise and an existing original story from that author

**Comment by skarempudi** [comment]
My Little Pony: Friendship is Magic, Equestria Girls, My Little Pony: the Movie (2017), My Little Pony: Friendship is Magic (IDW comics)

FimFiction: Each is a separate tag
FF.net: All of these are under My Little Pony. There are no separate movie and comic sections.
AO3: Separate tags for
My Little Pony - Seems to be a super tag that covers all other instances, since some tagged with this only actually have "My Little Pony: Friendship is Magic"
My Little Pony (Cartoon 1984-1989)
My Little Pony (Cartoon 2003-2009)
My Little Pony Tales (Cartoon 1992)
My Little Pony: Equestria Girls
My Little Pony: Friendship is Magic
My Little Pony: Pony Life (Cartoon)
My Little Pony: The Movie (2017)

**Comment by SigmasonicX** [comment]
My Little Pony: Friendship is Magic, Equestria Girls, My Little Pony: the Movie (2017), My Little Pony: Friendship is Magic (IDW comics)

FimFiction: Each is a separate tag

FF.net: All of these are under My Little Pony. There are no separate movie and comic sections.

AO3: Separate tags for
My Little Pony - Seems to be a super tag that covers all other instances, since some tagged with this only actually have "My Little Pony: Friendship is Magic"
My Little Pony (Cartoon 1984-1989)
My Little Pony (Cartoon 2003-2009)
My Little Pony Tales (Cartoon 1992)
My Little Pony: Equestria Girls
My Little Pony: Friendship is Magic
My Little Pony: Pony Life (Cartoon)
My Little Pony: The Movie (2017)

**Comment by SigmasonicX** [comment]
She-Ra: Princess of Power (80s), She-Ra and the Princesses of Power (10s)

FF.net:
She-Ra, Princess of Power
She-Ra and the Princesses of Power

AO3:
She-Ra: Princess Of Power (1985)
She-Ra and the Princesses of Power (2018)

**Comment by SigmasonicX** [comment]
Steven Universe, Steven Universe Future

FimFiction:
Steven Universe

FF.net:
Steven Universe

AO3:
Steven Universe (Cartoon)

**Comment by SigmasonicX** [comment]
Jojo's Bizarre Adventure: Phantom Blood, Jojo's Bizarre Adventure: Steel Ball Run, original JJBA story that has stands but no existing characters

FF.net:
JoJo's Bizarre Adventure

AO3:
ジョジョの奇妙な冒険 | JoJo no Kimyou na Bouken | JoJo's Bizarre Adventure 

Shockingly, differentiation between parts on AO3 is only handled by user tags. Some users add a tag for the part itself, but many just indicate the part via the character lists. It seems like entirely OC stories are still within that tag; and if a non-Jojo story has stands, it has a "Stands (JoJo)" user tag.

**Comment by SigmasonicX** [comment]
Cheers, Frasier

FF.net:
Cheers
Frasier

AO3:
Cheers (TV)
Frasier (TV)

**Comment by SigmasonicX** [comment]
Batman: the Animated Series, nonspecific Batman story, Batman v Superman: Dawn of Justice, Justice League (comics), Justice League (animated series), Justice League (2017), Zack Snyder's Justice League (2021)

FF.net:
Batman the Animated Series
Batman - listed in comics, used for both specific comic stories and nonspecific Batman
Batman v Superman: Dawn of Justice
Justice League - listed in comics, used for both specific comic stories and nonspecific Justice League
Justice League Unlimited - no listing for Justice League (animated series)
No listings for Justice League (2017), Zack Snyder's Justice League (2021)

AO3:
Batman: The Animated Series
Batman - All Media Types
Batman v Superman: Dawn of Justice
Justice League - All Media Types
Justice League & Justice League Unlimited (Cartoons)
Justice League (2017)
No listing for Zack Snyder's Justice League (2021)

**Comment by SigmasonicX** [comment]
Crossover between 6+ franchises

FimFiction:
Crossover tag without listing all the series

FF.net:
Can't handle crossovers between more than two things

AO3:
Tag for every single franchise

**Comment by SigmasonicX** [comment]
Crossover between a franchise and an existing original story from that author

FimFiction:
Unknown

FF.net:
Can't handle

AO3:
Tagged with that franchise and "Original Work", with user tags for the details of the original work

**Comment by SigmasonicX** [comment]
Checking Marvel Cinematic Universe included more complications. Copied from Discord:

Oh wait, my mistake, there are indeed "Marvel" and "Marvel Cinematic Universe" official tags
And it's a super tag for things like Runaways (TV 2017)
Marvel -> Marvel Cinematic Universe -> (Movie or show)
Though personally, this is a case where we don't have to quite go so far
I wouldn't want to expand this to like "Hasbro -> My Little Pony -> FiM" or anything like that
Also worth noting that on AO3, tags can have multiple parents
Marvel
|              \\
MCU    Avengers (All Media)
|               /
Avengers (MCU)

I don't think we need to do that
Also, AO3 doesn't actually show how tags connect

**Comment by Figments** [comment]
fandom tags should now be in place
