### ISSUE TITLE
Bottom of comment with quote goes out of bounds on mobile Google Chrome

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#372]
![image](https://user-images.githubusercontent.com/71996084/107184793-17308a00-6996-11eb-9d20-ae798c90af1d.png)
![image](https://user-images.githubusercontent.com/71996084/107184890-42b37480-6996-11eb-89e4-f0e42a9b12cb.png)
![image](https://user-images.githubusercontent.com/71996084/107184898-47782880-6996-11eb-90df-674c1e7f40f2.png)

This happens in portrait mode on Google Chrome on a mobile device. This doesn't happen in landscape mode, and hasn't been seen on computers yet.

This doesn't happen with comments without quotes.

**Comment by Figments** [comment]
this looks to be fixed with 0.7.0
