### ISSUE TITLE
Allow users to use the Browse page

### ISSUE THREAD

**Issue by Figments** [OffprintStudios/dragonfish#4]
The following functionality needs to be completed:

- [x] Display only *approved* and *published* works
- [x] Design story cards to display
    - [x] No cover art
    - [x] With cover art

**Comment by nisamson** [comment]
This seems like a special case of the search function to me, i.e. searching for any published story; does that sound about right?

**Comment by Figments** [comment]
Yeah. Searching for any published story, but with the added task of making at least a "New Stories" section sorted by date added.
