### ISSUE TITLE
Add additional details to audit sessions

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish#41]
AKA refresh tokens. Recording the gist of our talk in Discord for posterity:

Right now, audit sessions live forever. Ideally, an audit session should be
- the session ID
- the expiration date
- what device the user signed in to
- when the session was created

Which would allow cleaning them out after they've expired, and (eventually?) allowing a user to force-logout a session.

**Comment by Figments** [comment]
Only problem would be gathering the device information. Everything else would be relatively straightforward.
