### ISSUE TITLE
Editor slows down when there are around 7000 words

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#435]
If there are around 7000 words in the editor for a section or blog, then it takes several seconds to load, and typing in it greatly slows down. If, for example, I quickly wrote out that last sentence, then characters would keep appearing in the editor for several seconds after I finished typing.

**Comment by SigmasonicX** [comment]
This could be fixed by regenerating ckeditor.js, since that's currently set to version 23.0.0 and there was a fix for this issue in 25.0.0.
https://github.com/ckeditor/ckeditor5/releases/tag/v25.0.0

**Comment by SigmasonicX** [comment]
Still extant in dragonfish-next; above suggestion hasn't been applied yet.

**Comment by pingzing** [comment]
Long-term, we should import CKEditor as a git submodule, and create some "generate new version of CKEditor with all our plugins and custom settings" scripts, so that we can regenerate it at will with just stuff from our repo.

**Comment by Figments** [comment]
adding that we should re-add the embed media button now that we've got proper sanitization of media links

**Comment by SigmasonicX** [comment]
Addressed by https://github.com/OffprintStudios/dragonfish/pull/550 , but this didn't resolve the original issue.

**Comment by Figments** [comment]
we migrated to tiptap for our editor across the board, and we no longer have this issue.
