### ISSUE TITLE
Issues with dragonfish-next branch

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#460]
~~1. Go to a work with one or more sections, go into a section, then go back. The main page will no longer have sections listed. The sections are still there if you click the story title instead of going back.~~

~~2. Collections don't have working links, and the formatting doesn't look correct.~~

~~3. Settings page is missing the content filter settings and site appearance themes.~~

~~4. When you scroll to the bottom of any page, there is white space at the bottom. Every page has double scroll bars.~~

~~5. The header takes up a ton of space in user pages.~~

~~6. Add to Collection isn't implemented on works.~~

~~7. Site color schemes not implemented other than default.~~

~~8. In My Stuff, if you go to a section in Work A, then go to Work B, it will still display Work A's section.~~

**Comment by SigmasonicX** [comment]
Tickets I've left comments on
https://github.com/OffprintStudios/Sailfish/issues/110 - Behavior has changed
~~https://github.com/OffprintStudios/dragonfish/issues/284 - Resolved~~
~~https://github.com/OffprintStudios/dragonfish/issues/287 - Resolved~~
https://github.com/OffprintStudios/Sailfish/issues/104 - Still extant
https://github.com/OffprintStudios/dragonfish/issues/335 - Unable to recreate locally, will have to check on live site
~~https://github.com/OffprintStudios/dragonfish/issues/348 - Partially addressed~~
~~https://github.com/OffprintStudios/dragonfish/issues/424 - Resolved~~
~~https://github.com/OffprintStudios/dragonfish/issues/425 - Resolved via removal~~
https://github.com/OffprintStudios/dragonfish/issues/435 - Still extant
https://github.com/OffprintStudios/dragonfish/issues/436 - Still extant

**Comment by Figments** [comment]
numbers 1, 3, 4, and 7 are now fixed

**Comment by SigmasonicX** [comment]
Confirmed 1, 3 (moved to new global settings page), 4, and 7 are resolved.

Regarding 3, there is a new issue where the toggles don't match the current state of the content filters.

**Comment by SigmasonicX** [comment]
Issues:
~~1. Content filter toggles don't match the current state of the content filters.~~
~~2. Replying to comments isn't implemented~~
3. Create collection modal doesn't update "Private" next when toggle to public.
~~4. https://github.com/OffprintStudios/dragonfish/pull/461~~

**Comment by SigmasonicX** [comment]
~~5. Default style is nothing, so when users update, almost nothing is visible~~

**Comment by SigmasonicX** [comment]
~~6. No option to reply to your own comment~~
~~7. Canceling the creation of a Collection shouldn't refresh the page~~
~~8. Change Username isn't implemented~~

https://github.com/OffprintStudios/dragonfish/issues/336 - Still extant
~~https://github.com/OffprintStudios/dragonfish/issues/374 - Resolved~~
~~https://github.com/OffprintStudios/dragonfish/issues/412 - Resolved~~

Most tickets regarding comments involve replies, which I can't test right now.
