### ISSUE TITLE
Mobile optimizations for v0.7 design, including implementing sign in

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#468]
Currently, this is how the site looks on mobile. Note that the sign in button is inaccessible.
![image](https://user-images.githubusercontent.com/71996084/116632667-920d9f00-a90c-11eb-9f0c-4479d56eecf6.png)
![image](https://user-images.githubusercontent.com/71996084/116632678-9934ad00-a90c-11eb-8e2e-42864d2e9e94.png)
![image](https://user-images.githubusercontent.com/71996084/116632689-9fc32480-a90c-11eb-87b9-072d1c4d9a80.png)
![image](https://user-images.githubusercontent.com/71996084/116632700-a3ef4200-a90c-11eb-9543-0a22045535e3.png)
![image](https://user-images.githubusercontent.com/71996084/116632707-a8b3f600-a90c-11eb-9147-b5d47b189b41.png)

**Comment by Figments** [comment]
sign in has been addressed in latest update
