### ISSUE TITLE
Users find the log in button hard to locate

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#471]
Currently, the log in button is located on the bottom left. However, multiple users have reported they had a hard time finding it.

**Comment by SigmasonicX** [comment]
I suppose the best route for sign in would be to (1) put it at the top, (2) write Log In, but keeping the icon in addition to the text would be good

**Comment by Figments** [comment]
i think this might as well be solved with the new nav experience

we'll see what people say but for now i'm closing this
