### ISSUE TITLE
User complaints that the user profile page feels visually overwhelming with both horizontal and vertical bars

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#475]
https://www.fimfiction.net/group/215432/offprint/thread/468185/offprint-version-070-patch-notes#comment/7489326
![image](https://user-images.githubusercontent.com/71996084/116728683-10188700-a99b-11eb-974d-830b53786f29.png)

> Honestly, I find this whole screen a little confusing anyways (I'm not sure why some stuff is on the left rather than the top and vice-versa, for example.). I'll have to think about what could be improved on it. The me button could probably be a menu...

**Comment by Figments** [comment]
might've been partially addressed with the latest changes to portfolios, so i'm closing this until someone says they still feel it's too overwhelming
