### ISSUE TITLE
Work main pages display section title in browser bar if back into it

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#491]
Followup to https://github.com/OffprintStudios/dragonfish/pull/487 and https://github.com/OffprintStudios/dragonfish/issues/483 ,

There is still an issue with prose and poetry's main page. I'm setting the browser title in ngOnInit() and it works. However, if I go to a section (which still correctly sets the title in the live site) and then either back out or click the work title to go to the main page, the browser title still reflects the section I was on.

**Comment by Figments** [comment]
this is no longer the case
