### ISSUE TITLE
Create a generic "is user logged in" check

### ISSUE THREAD

**Issue by penguinstyles** [OffprintStudios/dragonfish#505]
Right now I'm using the following code block to check if a user is currently logged in. A simplified "userLoggedIn" (or similar) check should be created.

```
<div class="tools" *ngIf="currentUser$ | async as currentUser">
  <ng-container *ngIf="currentUser._id">
  </ng-container>
</ng-container>
```

**Comment by Figments** [comment]
this now exists in the current `main` version
