### ISSUE TITLE
When creating multiple sections in a row, new sections have the previous section's data

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#519]
User reported:
When creating sections back to back, it fills in the new section with the previous sections info. What I mean is I made a section, titled Prologue, and it has the prologue in the body. So I finish and save, make a new section for Chapter One and the new section is titled Prologue and has the body from the prologue. This is confusing because I don't know if I'm actually in a new section or editing the old section because the content is identical

**Comment by Figments** [comment]
didn't see this on my local environment, but we'll see if it's still an ongoing issue on the live site.
