### ISSUE TITLE
Edit button in My Stuff doesn't work for prose and poetry

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#522]
The edit button and the right click -> edit flow don't work for prose in My Stuff. Double clicking will work as expected, but the edit button instead takes you to a blank page.

The edit button works for blogs, but if you attempt to use the edit button for blogs immediately after using the edit button for prose, then it takes you to the "Create a Blog" page.

There is no action if you use the edit button for poetry.

**Comment by Figments** [comment]
fixed in #541
