### ISSUE TITLE
Logged out users can't access stories or news posts

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#534]
https://offprint.net/prose/7qx3bh_vKQM83vni7Bjz4/romancing-the-griffonstone
https://offprint.net/news/Rs5I6BkiRtVkHVrdnz5bL/last-week-on-offprint-may-9-2021

If users are logged out, these links don't work and will redirect to a blank page.

`ERROR Error: Uncaught (in promise): TypeError: t.ratings is null
fetchContent/<@https://offprint.net/main.ef683b4f5444c8506b16.js:1:1610967`

**Comment by Figments** [comment]
should be fixed with current `main` version
