### ISSUE TITLE
Log in expiring while in My Stuff can lead to confusing states

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#535]
![image](https://user-images.githubusercontent.com/71996084/118565882-d62fda80-b727-11eb-842a-46ef0ad6d40a.png)

When editing a blog post, this user was brought to an odd state where the edit blog page is empty and has to be filled out again. Then when he saved, an error message appeared. It was only after that that he realized he was logged out.

**Comment by Figments** [comment]
should be fixed with current `main` version
