### ISSUE TITLE
One VIP user couldn't save their VIP settings

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#536]
https://i.gyazo.com/f06ac00a87e4e415a6f58ca2430107d8.mp4

Update Tagline couldn't be set by this VIP user

(Description updated based on comment below)

**Comment by penguinstyles** [comment]
To be clear, when I experienced the above issue I _was_ already listed as a VIP on the supporter's page.

**Comment by Figments** [comment]
should be fixed with current `main` version
