### ISSUE TITLE
Security vulnerability reporting process

### ISSUE THREAD

**Issue by alyssarosenzweig** [OffprintStudios/dragonfish#540]
Hi,

If a vulnerability were found in dragonfish compromising Offprint user data, how should this be reported to maintain confidentiality while a fix is being written and replied?

In the mean time - let me know where best to reach @figments (I do not use Discord. I guess email then?)

Thanks,

Alyssa

**Comment by Figments** [comment]
the best way to reach me for stuff like that is figments@offprint.net
