### ISSUE TITLE
Copy/paste formatting issues

### ISSUE THREAD

**Issue by nisamson** [OffprintStudios/dragonfish#55]
- [x] Horizontal lines aren't carrying over, and there's no way to add them from the editor
- [x] Text remains the copied color (at least from Google docs), and there's no way to change the color to the theme's default; dark theme readers may not be able to read any of the story at all. 
![image](https://user-images.githubusercontent.com/7771080/89727521-92f74d00-d9da-11ea-9b56-c07a88f74224.png)

**Comment by Figments** [comment]
We might be able to fix the latter if we figure out a way to disallow colors in the editor, but some people want those colors so idk.

**Comment by Figments** [comment]
Fixed in 0.1.2
