### ISSUE TITLE
Address editor regressions following ckeditor update

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#558]
Relates to https://github.com/OffprintStudios/dragonfish/pull/550

Following the ckeditor update, users have reported drops in performance in the story editor. Particularly,

- When copying a story from Google Docs, extra newlines are added where previously they were parsed as single empty newlines.
- Editor performance slows even at 4000 words, compared to 7000 like before in https://github.com/OffprintStudios/dragonfish/issues/435
- Potentially https://github.com/OffprintStudios/dragonfish/issues/552

A temporary solution would be to revert the ckeditor to what it was before.

**Comment by Figments** [comment]
temporary solution was implemented; we'll wait and see what future updates to CKEditor add to assist with these problems
