### ISSUE TITLE
Better handle being logged out on My Stuff, or address potential issue causing log outs in My Stuff

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#603]
User reported issue:
Hey, I think I found an actual bug trying to add one of my stories from FIMFic earlier.
Okay, so under My Stuff -> Create Prose, after filling in the descriptions and stuff, I click save. A pop-up appears saying 'saved'. All good so far.
I try to upload a cover by drag&drop (And no, I didn't click that section first >.< ) Firefox opens the image instead.
Sigh, hit the back button, and everything's vanished.
Click home, go back to my stuff, and nothing's there.
Fill everything out again, and proceed to make the exact same mistake, 'cause I'm a moron.
Still nothing on 'my stuff'.
Everything worked fine the third time though, 'cause I didn't screw up.
Though, later I realise I've been logged out for some reason, and after logging back in I can see all three attempts
Deleting the extras didn't seem to work at first, but they're gone now.
And I also made a test story while typing this up, to reproduce the bug, and that one deleted straight away.

My takeaway from this is that My Stuff doesn't handle alerting the user that they've been logged out well. Alternatively, there could be an issue causing users to get logged out, and we should address that.

**Comment by Figments** [comment]
My Stuff no longer exists
