### ISSUE TITLE
Site functionality without frontend JavaScript

### ISSUE THREAD

**Issue by alyssarosenzweig** [OffprintStudios/dragonfish#61]
Issue to track functionality of the _frontend_ site with JavaScript disabled. While the majority of users can use JavaScript, a minority may not be able to for various reasons (users of text-based browsers, security-conscious users who disable to reduce attack surface, low-resource browsers used on older devices where disabling JavaScript is a needed optimization, etc.) Additionally, interactive elements can complicate accessibility to e.g. screen readers. As such, the frontend should function without JavaScript to accommodate these users.

Currently, with JavaScript disabled the site gives a blank page. Let's change that :)

**Comment by alyssarosenzweig** [comment]
I'm looking into how to accomodate this with the least invasive changes. The site HTML is currently rendered client-side; that would need to be pushed to a server before even considering fancier interactive features. 

One aggressive approach would be to have a separate "Offprint Lite" site that consumes the regular backend API but is otherwise independent. From the perspective of existing code, that is the least disruptive, since the main frontend can forget this use case. It also has the benefit of enabling additional optimizations specifically with low-resource and text-based (incl. screen readers) browsers in mind. The drawback is that this alternate frontend may be missing features / get easily forgotten, dividing the user base.

**Comment by Figments** [comment]
There's still the possibility of using Angular Server-side Rendering in order to at the very least facilitate serving page HTML on first request and loading the JavaScript later, but that still doesn't solve the problem of users who want to disable *all* JavaScript from accessing the website normally.

Honestly, short of abandoning Angular entirely for the frontend, I don't know how we would be able to accommodate users who do not wish to enable JavaScript.

**Comment by alyssarosenzweig** [comment]
Right, I see that. The good news is that the backend exposes quite a lovely API and everything seems neatly decoupled, so if we put aside the synchronization issues, prototyping alternative frontends seems very doable. I'm not at all sure what'll come of the experiment but if you'd like to assign this issue to me I'd like to poke at it.

**Comment by Figments** [comment]
Sure thing!

**Comment by alyssarosenzweig** [comment]
https://gemfic.xyz does what I was envisioning when I opened this issue, by way of native gemini support at gemini://gemfic.xyz ... very happy to close this now! thank you for the support and for offprint :)
