### ISSUE TITLE
Improve navigation from My Stuff to public story page

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#616]
User request:
A double-click takes me to the screen with the edit/delete buttons, and a place to put a cover. (which I'm not going to bother with for poetry, but I appreciate that some people will)
It also still has a little icon telling me I have a comment, but no (obvious) way to view it from here.
Instead I have to go back to my stuff, right-click the poem, click 'get public link', and paste that into the address bar.
...Now there's nothing about this that particularly feels like a bug, but I just wanted to rant about it 'cause it's kinda dumb from a UX point of view.

**Comment by Figments** [comment]
My Stuff doesn't exist anymore
