### ISSUE TITLE
Add support for alt accounts linked to the main account

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#638]
This ticket is to provide official support for alternate accounts, which are linked to the main account. Users may use these alt accounts to post content they don't want on their primary account.
- On the user end, accounts will share a single sign-in.
- Users will have a primary account and some number of alt accounts.
- Works, blogs, and collections can be tied to one of these alt accounts. They won't be displayed on the main account, but rather this alt account. For at least collections, the same collection can be set to display across all accounts.
- Whether the alt account links back to the primary account for other users can be set by the user.
- On the moderation end, it will be easy to tell what the primary account is for an alt account, so they can moderate appropriately.

**Comment by Figments** [comment]
this has been formally implemented with the pseudonyms update
