### ISSUE TITLE
Extra newlines in editor aren't reflected in the published work; same for tabs and other whitespace

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#648]
User reported
![image](https://user-images.githubusercontent.com/71996084/129837895-77d0a38b-34c3-4292-816f-1a578ba111cd.png)
![image](https://user-images.githubusercontent.com/71996084/129837900-75314398-b876-4063-84cb-ba4ca1fa1121.png)

If a work's editor has extra newlines, those are removed in the published view of that work. The extra newlines remain in the editor even after publishing.

Some authors deliberately include extra newlines for effect.

EDIT: Workaround discovered: extra newlines created with Shift+Enter aren't stripped out. It's possible we'll want to leave it at that, and leave documentation about this on a writing guide in the future.

This also applies to extra whitespace like tabs before paragraphs.

**Comment by Figments** [comment]
this should no longer happen
