### ISSUE TITLE
Section editing freezes when save then go to a different section

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/dragonfish#651]
User reported
I had reported the problem that when I have edit view open on a chapter, then click to a different chapter, it freezes. Then I said never mind because I couldn't replicate the problem. Now it's happening every time again
Okay, figured out why I couldn't recreate it before. You need to go into the editor, change something, save it, then switch to a different section without switching out of edit mode
![image](https://user-images.githubusercontent.com/71996084/130369981-4f45ef70-874c-4203-a451-40c300e48877.png)
This is frozen in this position
The only solution is to close the tab and just reopen it fresh

**Comment by Figments** [comment]
this should no longer happen
