### ISSUE TITLE
Allow users to use the search box to browse the site's content

### ISSUE THREAD

**Issue by Figments** [OffprintStudios/dragonfish#7]
The following functionality needs to be completed: 

- [x] Search input field sends data correctly to the backend
- [x] Search page needs to be designed to accommodate users, works, and blogs
- [x] ONLY RETRIEVES PUBLISHED/APPROVED CONTENT

**Comment by nisamson** [comment]
I can take a look at this. Do you have any particular thoughts for the search DSL?

**Comment by Figments** [comment]
Something like 
```TypeScript
await this.searchService.findAllRelated(query);
```
where `findAllRelated()` is just an aggregate function pulling together the results from `blogsService.findAllRelated(query)`, `usersService.findAllRelated(query)` and `worksService.findAllRelated(query)`.

An example query would be like, `this.userModel.find().where('username', query);` or something similar, though you might want to take a look in the Mongoose API docs to figure out stuff like "find everything similar to this".

**Comment by Figments** [comment]
Some things to consider, seeing as this will be necessary for future reference:

https://stackoverflow.com/questions/28775051/best-way-to-perform-a-full-text-search-in-mongodb-and-mongoose

**Comment by nisamson** [comment]
Yeah, what I meant was more, how do we want this to look in the search box?

There's derpi style, with `A, B, -C` translating to `Tag<A> AND Tag<B> AND NOT Tag<C>`.

Obviously, we also have text, so textual search makes sense in there. Maybe something more akin to Discord's?

`beans author:Figments type:Blog`

For MVP, we could just take the dumb route and treat everything like the user just wants to search in the text.

**Comment by nisamson** [comment]
If we're smart about how this is implemented, this makes the API queries nice and easy (and we can shove parsing on the client end)

**Comment by Figments** [comment]
Oop, sorry! Misunderstood what you meant. 

Yeah, I think for MVP, simple text searches are fine. We can investigate search shortcuts like what you've proposed for a future update, but for now it's best to just get it working at a bare minimum level.

**Comment by nisamson** [comment]
Do we want to split up the words into tokens and remove stop words? That would turn a query like
"The problem with bees is that they aren't nice"
into
`[problem, bees, nice]`

**Comment by Figments** [comment]
Yeah! Let's try that, and if it's straightforward enough to implement, we'll keep it for launch.

**Comment by Figments** [comment]
This is getting delayed to the next big update, Origins pt.2.

Sorry to everyone expecting this at launch :<
